version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project/backend
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py test